image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install dependencies (prebuild)
    init: |
      # 如果有 composer.json，预构建时安装依赖
      if [ -f composer.json ]; then composer install --no-interaction --no-dev; fi
      # 环境文件：若没有 .env 则复制示例（你可能需要手动编辑）
      if [ -f .env.example ] && [ ! -f .env ]; then cp .env.example .env; fi
    command: |
      # 启动 PHP 内建服务器，指向 public 目录（ThinkPHP5 常见入口）
      php -S 0.0.0.0:8080 -t public

ports:
  - name: Web App
    port: 8080
    onOpen: open-browser
    visibility: public
