image:
  file: .gitpod.Dockerfile

tasks:
  - name: Init & Start PHP Server
    init: |
      # 如果有 composer.json，就安装依赖
      if [ -f composer.json ]; then composer install --no-interaction --no-dev; fi
      
      # 复制环境文件
      if [ -f .env.example ] && [ ! -f .env ]; then cp .env.example .env; fi
    command: |
      # 启动 PHP 内置服务器（指向 public 目录）
      php -S 0.0.0.0:8080 -t public

ports:
  - port: 8080
    onOpen: open-preview
